# Generated by Django 5.2.6 on 2025-09-14

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=50, unique=True, verbose_name='사번')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='이름')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='질병명')),
                ('health', models.TextField(blank=True, null=True, verbose_name='건강고지형')),
                ('general', models.TextField(blank=True, null=True, verbose_name='일반고지형')),
                ('simple', models.TextField(blank=True, null=True, verbose_name='간편고지형')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, unique=True, verbose_name='회사명')),
                ('callCenter', models.CharField(blank=True, max_length=50, null=True, verbose_name='콜센터')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='팩스')),
                ('termsUrl', models.URLField(blank=True, null=True, verbose_name='공시실 URL')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='보험 종류')),
                ('highlight', models.BooleanField(default=False, verbose_name='강조 여부')),
            ],
        ),
        migrations.CreateModel(
            name='Fetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=255, unique=True, verbose_name='질병명')),
                ('current', models.TextField(blank=True, null=True, verbose_name='현증')),
                ('history', models.TextField(blank=True, null=True, verbose_name='과거력/치료력')),
                ('documents', models.TextField(blank=True, null=True, verbose_name='필요서류')),
            ],
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='상품명')),
                ('plan', models.CharField(max_length=255, verbose_name='플랜명')),
                ('coverage', models.CharField(max_length=255, verbose_name='담보명')),
                ('minAge', models.IntegerField(verbose_name='최소 연령')),
                ('maxAge', models.IntegerField(verbose_name='최대 연령')),
                ('amount', models.CharField(max_length=50, verbose_name="가입금액 한도")),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(max_length=100, null=True, blank=True)),  # 세션 사용자명
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
